version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: peterson
    ports:
      - 5432

  web:
    build: .
    command: sh start.sh
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
      - worker

  worker:
    build: .
    command: sh start.sh
    environment:
      WORKER: 'true'
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'petersondaronch@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'bumblebee'
      PGADMIN_LISTEN_PORT: '8080'
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  gems:
